---

- name: Create directory with recursive
  file:
    state: directory
    path: "{{ pip_offline_dir }}"
    recurse: true
  become: true

- name: create directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
  with_items:
    - "{{ pip_offline_dir }}/pypi"
  become: true

- name: Get pip version
  command: pip --version
  register: pip_version
  changed_when: false
  ignore_errors: true
  no_log: true

- name: Install python-pip
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ python_pip_packages }}"
  when: "(pip_version is failed)"
  become: true

- name: archive pypi folder
  archive:
    path: "{{ role_path }}/files/pypi"
    dest: "{{ pip_offline_dir }}/pypi.tar.gz"
  delegate_to: localhost
  connection: local
  run_once: true
  become: true

- name: copy pip packages
  unarchive:
    src: "{{ pip_offline_dir }}/pypi.tar.gz"
    dest: "{{ pip_offline_dir }}"
  become: true

- name: Install pip packages
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: present
    extra_args: "-U --no-index --find-links file://{{ pip_offline_dir }}/pypi"
  with_items: "{{ pip_packages }}"
  become: true
