---

- name: Include platform specific vars
  include_vars: "{{item}}"
  with_first_found:
    - files:
        - "{{ansible_distribution}}.yml"
        - "{{ansible_os_family}}.yml"
      skip: true

- import_tasks: install.yml
- import_tasks: config.yml
- import_tasks: sni.yml
  when: ansible_python_version is version_compare('2.6.0', '>=')
    and ansible_python_version is version_compare('2.7.9', '<')
