---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: pip_debian9
    image: amd64/debian:stretch
  - name: pip_ubuntu18_04
    image: amd64/ubuntu:bionic
provisioner:
  name: ansible
  options:
    diff: true
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
